version: "3.9"

services:
  # MySQL 5.6 for my work environment
  mysql56:
    container_name: mysql56
    image: mysql:5.6
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    ports:
      - ${MYSQL56_PORT}:3306
    volumes:
      - ./volumes/mysql56:/var/lib/mysql

  mysql:
    container_name: mysql
    image: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    ports:
      - ${MARIADB_PORT}:3306
    volumes:
      - ./volumes/mariadb:/var/lib/mariadb

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: unless-stopped
    depends_on:
      - "mysql"
      # - "mariadb"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      # - PMA_HOST=mariadb
    ports:
      - ${PMA_PORT}:80

  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - "postgres"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - ./volumes/pgadmin4:/var/lib/pgadmin
      - ./volumes/pgadmin4:/certs/server.cert
      - ./volumes/pgadmin4:/certs/server.key
      - ./volumes/pgadmin4:/pgadmin4/servers.json

  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: admin
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./volumes/mongo:/data/db
      - ./volumes/mongo-config:/data/configdb

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: unless-stopped
    depends_on:
      - "mongo"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_SERVER: "mongo"
    ports:
      - ${MONGO_EXPRESS_PORT}:8081

  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./volumes/redis:/data

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander
    restart: unless-stopped
    depends_on:
      - "redis"
    environment:
      REDIS_HOST: redis
    ports:
      - ${REDIS_COMMANDER_PORT}:8081

networks:
  default:
    external:
      name: ${EXTERNAL_NETWORK_NAME}
