services:
  # MySQL 5.6 for my work environment
  mysql56:
    container_name: ${COMPOSE_PROJECT_NAME}-mysql56
    image: mysql:5.6.51
    restart: unless-stopped
    stdin_open: true
    tty: true
    privileged: true
    user: "${DOCKER_USER_UID}:${DOCKER_USER_GID}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASS}
    ports:
      - 127.0.0.1:${MYSQL56_PORT}:3306
    volumes:
      - ./volumes/mysql56:/var/lib/mysql:rw
    command: --default-authentication-plugin=mysql_native_password
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}-mariadb
    image: mariadb:11.5.2-ubi9
    restart: unless-stopped
    stdin_open: true
    tty: true
    privileged: true
    user: "${DOCKER_USER_UID}:${DOCKER_USER_GID}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASS}
    ports:
      - 0.0.0.0:${MARIADB_PORT}:3306
    volumes:
      - ./volumes/mariadb:/var/lib/mysql:rw

  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    image: postgres:16.4-alpine3.20
    restart: unless-stopped
    stdin_open: true
    tty: true
    privileged: true
    user: "${DOCKER_USER_UID}:${DOCKER_USER_GID}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    ports:
      - 0.0.0.0:${POSTGRES_PORT}:5432
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data:rw

  valkey:
    container_name: ${COMPOSE_PROJECT_NAME}-valkey
    image: valkey/valkey:7.2.6-alpine3.20
    restart: unless-stopped
    stdin_open: true
    tty: true
    privileged: true
    user: "${DOCKER_USER_UID}:${DOCKER_USER_GID}"
    ports:
      - 0.0.0.0:${VALKEY_PORT}:6379
    volumes:
      - ./volumes/valkey:/data:rw

networks:
  default:
    name: ${EXTERNAL_NETWORK_NAME}
    external: true
